<template>
    <main class="page--container delay-page__container">
        <div class="delay-page">
            <h1>Delay</h1>
            <p>A delay between multiple objects creates a sense of fluidity and layered motion.</p>
            
            <section>
                <div class="delay-softness">
                    <Roulette 
                        :data="cards"
                        v-slot="slotProps" 
                        @change="setData" 
                    >
                        <div class="card">
                            <div class="image--container">
                                <img :src="`https://picsum.photos/seed/${slotProps.data}/600/200`">
                            </div>
                            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maiores quaerat id quisquam aperiam at, qui quis quos necessitatibus ex, error vero, cumque sint consequatur.</p>
                        </div>
                    </Roulette>
                    <p>- Pictures are randomly generated by <a target="_blank" href="https://picsum.photos/">Lorem Picsum</a></p>
                </div>
            </section>
            
            <section>
                <div class="delay-hierarchy">
                    <h2>Hierarchy</h2>
                    <p> This approach also guides the user's focus, highlighting an object's position within the hierarchy of elements.</p>

                    <div class="hierarchy--container">
                        <RouterView></RouterView>
                    </div>
                </div>
            </section>   
        </div>
    </main>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue';
import gsap from 'gsap';
import Roulette from '../../components/delay/Roulette.vue';

// Simulate fake data by generating numbers for random images
const NUM_CARDS_PER_PAGE = 4
const activeCardRange = ref(NUM_CARDS_PER_PAGE);
const cards = computed(() => {
    const start = ((activeCardRange.value / NUM_CARDS_PER_PAGE) - 1) * NUM_CARDS_PER_PAGE;
    const arr = [];
    for (let i = start + 1; i <= activeCardRange.value; i++) {
        arr.push(i);
    }
    return arr;
});

const setData = (rouletteDirection) => {
    const operation = rouletteDirection === "prev" ? -1 : 1;
    const newRange = activeCardRange.value + (NUM_CARDS_PER_PAGE * operation);
    
    if (newRange !== 0) {
        activeCardRange.value = newRange;
    }
    else activeCardRange.value = NUM_CARDS_PER_PAGE;
}

const createTimeLine = () => {
    gsap.timeline({
    })
    .from('.delay-page > h1', {
        y: 40,
        opacity: 0,
        duration: 1,
        ease: 'power3.out'
    })
    .from('.delay-page > p', {
        y: 30,
        opacity: 0,
        duration: 1,
        ease: 'power3.out'
    }, "<30%");
}

onMounted(async () => {
    createTimeLine();
})
</script>

<style lang="scss" scoped>

.delay-page__container {
    padding-block: 22px;
    display: grid;
    grid-template-columns: repeat(12, 1fr);
    overflow-y: scroll;
    @include mixins.scroller;
}

.delay-page {
    grid-column: 2 / -2;
    
    display: flex;
    flex-direction: column;
    gap: 12px;

    h1 {
        font-size: var(--font-4);
        border-bottom: 2px solid var(--slate-6);
    }

    p {
        width: 60%;
        letter-spacing: 1px;
        line-height: 1.6;
    }

    section {
        flex-shrink: 0;
        height: 100%;

        margin-top: 12px;
    }
}

.delay-softness {
    height: 100%;

    display: flex;
    flex-direction: column;
    gap: 12px;

    .card {
        height: 100%;
        
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        
        border: 1px solid var(--slate-2);
        border-radius: 4px 4px 0 0;
        overflow: hidden;
        
        .image--container {
            height: 200px;
            width: 100%;
            
            img {
                width: 100%;
            }
        }
        
        p {
            letter-spacing: revert;
            padding: 12px 8px;
            width: 100%;
            backdrop-filter: blur(3px);
            background-color: hsla(240, 6%, 7%, 0.9);
        }
    }

    & > p {
        color: var(--slate-10);

        a {
            color: var(--slate-11);
            text-decoration: none;
            border-bottom: 1px solid var(--slate-12);

            &:visited {
                color: var(--slate-12);
            }
        }
    }
}

.delay-hierarchy {
    height: 100%;
    display: flex;
    flex-direction: column;
    gap: 12px;

    h2 {
        font-size: var(--font-3);
        border-bottom: 2px solid var(--slate-3);
    }

    .hierarchy--container {
        flex: 1;
        // background-color: blue;
    }
}
</style>