<template>
    <main class="page--container delay-page__container">
        <div class="header">
            <h1>Delay</h1>
            <p>A delay between multiple objects creates a sense of fluidity and layered motion.</p>
        </div>
        
        <section class="delay-softness">
            <Roulette 
                :data="cards"
                v-slot="slotProps" 
                @change="setData" 
            >
                <div class="card">
                    <div class="image--container">
                        <img :src="`https://picsum.photos/seed/${slotProps.data}/600/250`">
                    </div>
                    <p>Lorem ipsum dolor.</p>
                </div>
            </Roulette>
            <p>- Pictures are randomly generated by <a target="_blank" href="https://picsum.photos/">Lorem Picsum</a></p>
        </section>
        
        <section class="delay-hierarchy">
            <h2>Hierarchy</h2>
            <p> This approach also guides the user's focus, highlighting an object's position within the hierarchy of elements.</p>

            <div class="hierarchy--container">
                <RouterView></RouterView>
            </div>
        </section>
    </main>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue';
import gsap from 'gsap';
import Roulette from '../../components/delay/Roulette.vue';

// Simulate fake data by generating numbers for random images
const NUM_CARDS_PER_PAGE = 4
const activeCardRange = ref(NUM_CARDS_PER_PAGE);
const cards = computed(() => {
    const start = ((activeCardRange.value / NUM_CARDS_PER_PAGE) - 1) * NUM_CARDS_PER_PAGE;
    const arr = [];
    for (let i = start + 1; i <= activeCardRange.value; i++) {
        arr.push(i);
    }
    return arr;
});

const setData = (rouletteDirection) => {
    const operation = rouletteDirection === "prev" ? -1 : 1;
    const newRange = activeCardRange.value + (NUM_CARDS_PER_PAGE * operation);
    
    if (newRange !== 0) {
        activeCardRange.value = newRange;
    }
    else activeCardRange.value = NUM_CARDS_PER_PAGE;
}

const createTimeLine = () => {
    gsap.timeline({
    })
    .from('.header > h1', {
        y: 40,
        opacity: 0,
        duration: 1,
        ease: 'power3.out'
    })
    .from('.header > p', {
        y: 30,
        opacity: 0,
        duration: 1,
        ease: 'power3.out'
    }, "<30%");
}

onMounted(async () => {
    createTimeLine();
})
</script>

<style lang="scss" scoped>
.delay-page__container {
    display: grid;
    grid-template-columns: repeat(12, 1fr);
    grid-template-rows: 100px 100% 100%;
    row-gap: 32px;
    padding-top: 22px;

    overflow-y: scroll;
    @include mixins.scroller;

    & > * {
        grid-column: 2 / -2;
    }
}

.header {
    display: flex;
    flex-direction: column;
    gap: 8px;

    h1 {
        height: 80px;
        font-size: var(--font-4);
        border-bottom: 2px solid var(--slate-6);
    }
    
    p {
        width: 60%;
        letter-spacing: 1px;
        line-height: 1.6;
    }
}

section {
    width: 100%;
    height: 100%;
}

.delay-softness {
    display: flex;
    flex-direction: column;
    gap: 22px;

    .card {
        width: 100%;

        display: flex;
        flex-direction: column;
        gap: 12px;
        
        border: 1px solid var(--slate-2);
        border-radius: 4px 4px 0 0;

        .image--container {
            height: 250px;

            img {
                width: 100%;
                height: 100%;
            }
        }
        
        p {
            padding: 12px 8px;
            width: 100%;
        }
    }

    & > p {
        color: var(--slate-12);

        a {
            font-weight: 800;
            color: var(--slate-11);
            text-decoration: none;
            border-bottom: 1px solid var(--slate-12);

            &:visited {
                color: var(--slate-12);
            }
        }
    }
}

.delay-hierarchy {
    height: 100%;
    display: flex;
    flex-direction: column;
    gap: 12px;

    h2 {
        font-size: var(--font-3);
        border-bottom: 2px solid var(--slate-3);
    }

    p {
        margin-bottom: 22px;
    }

    .hierarchy--container {
        height: 100%;
    }
}
</style>